Frontend_PruebaCRUD_Persona/Models/ErrorViewModel.cs
using System;

namespace Frontend_PruebaCRUD_Persona.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Frontend_PruebaCRUD_Persona/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Frontend_PruebaCRUD_Persona.Models;

namespace Frontend_PruebaCRUD_Persona.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Frontend_PruebaCRUD_Persona/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Frontend_PruebaCRUD_Persona.Controllers
{
    public class PersonasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Frontend_PruebaCRUD_Persona/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Frontend_PruebaCRUD_Persona/Views/Personas/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div id="personas">
    <v-app>
        <v-dialog>

            <v-card>
                <v-card-title>Eliminación de persona</v-card-title>
                <v-card-text>
                    ¿Desea eliminar a la persona?
                </v-card-text>
                <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn text v-on:click>Cancelar</v-btn>
                    <v-btn text>Eliminar</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>
        <v-dialog v-model="edicionDialogo">
            <v-card>
                <v-card-title>Edición de persona</v-card-title>
                <v-card-text>
                    <v-text-field outlined label="Nombres"
                                  v-model="persona.nombres">

                    </v-text-field>
                    <v-text-field outlined label="Apellidos"
                                  v-model="persona.apellidos">

                    </v-text-field>
                    <v-text-field outlined label="DPI"
                                  v-model="persona.dpi">

                    </v-text-field>

                    <v-text-field outlined label="Dirección"
                                  v-model="persona.direccion">

                    </v-text-field>
                    <v-checkbox label="Género" v-model="persona.genero">

                    </v-checkbox>
                    <v-text-field outlined label="Fecha nacimiento"
                                  v-model="persona.fechanacimiento">

                    </v-text-field>
                    <v-text-field outlined label="Escolaridad"
                                  v-model="persona.escolaridad">

                    </v-text-field>
                    <v-checkbox label="Activo" v-model="persona.activo">

                    </v-checkbox>
                </v-card-text>
                <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn text v-on:click="edicionDialogo=false">Cancelar</v-btn>
                    <v-btn text>Editar</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>
        <h1>Index</h1>

        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Nombres
                    </th>
                    <th>
                        Apellidos
                    </th>
                    <th>
                        Dpi
                    </th>
                    <th>
                        Dirección
                    </th>
                    <th>
                        Género
                    </th>
                    <th>
                        Fecha de nacimiento
                    </th>
                    <th>
                        Escolaridad
                    </th>
                    <th>
                        Activo
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="(persona,index) in personasData">
                    <td>
                        {{persona.nombres}}
                    </td>
                    <td>
                        {{persona.apellidos}}
                    </td>
                    <td>
                        {{persona.dpi}}
                    </td>
                    <td>
                        {{persona.direccion}}
                    </td>
                    <td>
                        {{persona.genero}}
                    </td>
                    <td>
                        {{persona.fechaNacimiento}}
                    </td>
                    <td>
                        {{persona.escolaridad}}
                    </td>
                    <td>
                        {{persona.activo}}
                    </td>
                    <td>
                        <button v-on:click="onedit">Editar</button>
                        <button v-on:click="ondelete">Eliminar</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </v-app>
</div>
@section Scripts{ 

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"></script>

<script>
        var app = new Vue({
            el: '#personas',
            vuetify: new Vuetify(),
            data: {
                personasData: [],
                edicionDialogo: false,
                eliminacionDialogo:false,
                persona: {
                    nombres: "",
                    apellidos: "",
                    dpi: "",
                    direccion: "",
                    genero: false,
                    fechaNacimiento: "",
                    escolaridad: "",
                    activo:false
                }
            },
            methods: {
                onedit() {
                    this.edicionDialogo = true;
                },
                ondelete() {
                    console.log("eliminar");
                },
                loadPersonas() { return axios.get("https://localhost:44301/Personas") },
                async loadAll() {
                    axios.all([this.loadPersonas()]).then((response) => {
                        if (response[0].status == 200)
                            if (response[0].data.code == 1) 
                                this.personasData = response[0].data.data;
                    });
                }
            },
            created() {
                this.loadAll();
                console.log("creado personas");
            }
        })
</script>
}

Frontend_PruebaCRUD_Persona/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frontend_PruebaCRUD_Persona</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@('@')mdi/font@latest/css/materialdesignicons.min.css">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons" rel="stylesheet">
    <script src="https://apis.google.com/js/api.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Frontend_PruebaCRUD_Persona</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personas" asp-action="Index">Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @RenderSection("Scripts", required: false)
    @RenderSection("Styles",required:false)
</body>
</html>